# Generated by Django 6.1 on 2026-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
