# Generated by Django 6.1 on 2026-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=7, unique=True)),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                        ],
                        default="INACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
    ]
