# Generated by Django 6.1 on 2026-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_financialperiod"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="financialperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("status",),
                name="only_one_active_financial_period",
            ),
        ),
    ]
